In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns

In [ ]:
k=[4,2.56789,9,87.9999,40,'hyderabad']
k

[4, 2.56789, 9, 87.9999, 40, 'hyderabad']

In [ ]:
pd.Series(k)

0            4
1      2.56789
2            9
3      87.9999
4           40
5    hyderabad
dtype: object

In [ ]:
a=np.random.randint(20,50,15)
a

array([35, 37, 45, 37, 23, 29, 44, 29, 48, 32, 48, 31, 25, 42, 28])

In [ ]:
a.ndim

2

In [ ]:
pd.Series(a)

0     35
1     37
2     45
3     37
4     23
5     29
6     44
7     29
8     48
9     32
10    48
11    31
12    25
13    42
14    28
dtype: int64

In [ ]:
a=np.random.randint(20,50,(5,4))
a

array([[41, 29, 48, 38],
       [45, 32, 40, 38],
       [49, 21, 40, 32],
       [38, 45, 22, 38],
       [46, 44, 39, 31]])

In [ ]:
b=np.random.randint(100,200,(6,5))
b.ndim

2

In [ ]:
b.shape

(6, 5)

In [ ]:
b

array([[143, 128, 160, 101, 113],
       [158, 133, 191, 181, 122],
       [124, 168, 162, 118, 110],
       [101, 166, 159, 138, 178],
       [122, 198, 107, 131, 105],
       [181, 193, 101, 199, 121]])

In [ ]:
np.random.seed(34)
b=np.random.randint(100,200,60)
b

array([133, 185, 168, 135, 169, 111, 178, 129, 118, 129, 189, 129, 120,
       196, 162, 105, 120, 151, 119, 185, 121, 163, 172, 142, 184, 172,
       177, 136, 102, 137, 198, 158, 142, 175, 134, 158, 162, 138, 188,
       166, 170, 142, 196, 143, 185, 131, 184, 189, 162, 184, 190, 157,
       177, 144, 119, 193, 138, 123, 109, 113])

In [ ]:
pd.Series(b)

0     133
1     185
2     168
3     135
4     169
5     111
6     178
7     129
8     118
9     129
10    189
11    129
12    120
13    196
14    162
15    105
16    120
17    151
18    119
19    185
20    121
21    163
22    172
23    142
24    184
25    172
26    177
27    136
28    102
29    137
30    198
31    158
32    142
33    175
34    134
35    158
36    162
37    138
38    188
39    166
40    170
41    142
42    196
43    143
44    185
45    131
46    184
47    189
48    162
49    184
50    190
51    157
52    177
53    144
54    119
55    193
56    138
57    123
58    109
59    113
dtype: int64

In [ ]:
df=pd.DataFrame(b)
df

      0
0   133
1   185
2   168
3   135
4   169
5   111
6   178
7   129
8   118
9   129
10  189
11  129
12  120
13  196
14  162
15  105
16  120
17  151
18  119
19  185
20  121
21  163
22  172
23  142
24  184
25  172
26  177
27  136
28  102
29  137
30  198
31  158
32  142
33  175
34  134
35  158
36  162
37  138
38  188
39  166
40  170
41  142
42  196
43  143
44  185
45  131
46  184
47  189
48  162
49  184
50  190
51  157
52  177
53  144
54  119
55  193
56  138
57  123
58  109
59  113

In [ ]:
np.random.seed(34)
b=np.random.randint(100,200,(6,5))
b

array([[133, 185, 168, 135, 169],
       [111, 178, 129, 118, 129],
       [189, 129, 120, 196, 162],
       [105, 120, 151, 119, 185],
       [121, 163, 172, 142, 184],
       [172, 177, 136, 102, 137]])

In [ ]:
pd.Series(b)

ValueError: Data must be 1-dimensional, got ndarray of shape (6, 5) instead

In [ ]:
df=pd.DataFrame(b,columns=['Roll','name','adds','age','country'],index=[182,183,184,185,186,187])
df

ValueError: Shape of passed values is (60, 1), indices imply (6, 5)

In [ ]:
df.iloc[0]

0    133
Name: 0, dtype: int64

In [ ]:
df.loc[133]

KeyError: 133

In [ ]:
df.iloc[0,0]

133

In [ ]:
df.loc[185,'Roll']

KeyError: 'Roll'

In [ ]:
df.iloc[185,'Roll','name','age']

IndexingError: Too many indexers

In [ ]:
df.loc[[182,186,187]]

KeyError: "None of [Index([182, 186, 187], dtype='int64')] are in the [index]"

In [ ]:
df.loc[[133,185,168],['adds','name','Roll']]

KeyError: "None of [Index([133, 185, 168], dtype='int64')] are in the [index]"

In [ ]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [ ]:
sns.load_dataset('titanic')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
sns.load_dataset('diamonds')

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [ ]:
sns.load_dataset('flights')

     year month  passengers
0    1949   Jan         112
1    1949   Feb         118
2    1949   Mar         132
3    1949   Apr         129
4    1949   May         121
..    ...   ...         ...
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

[144 rows x 3 columns]

In [ ]:
df.iloc[0.0:3]

TypeError: cannot do positional indexing on RangeIndex with these indexers [0.0] of type float

In [ ]:
df.iloc[0[0,1,2]]

<>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
<>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
<ipython-input-48-2ed47e106b66>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
  df.iloc[0[0,1,2]]

TypeError: 'int' object is not subscriptable